export default function listImages() {
return [
{ description: "3d render of a programmer fighting a bug", file: "./images/3d render of a programmer fighting a bug.png" },
{ description: "A raccoon in an office throwing chairs", file: "./images/A raccoon in an office throwing chairs.png" },
{ description: "Abstract Echos at a Dance Club", file: "./images/Abstract Echos at a Dance Club.png" },
{ description: "Banner of deep learning and machine learning imagery", file: "./images/Banner of deep learning and machine learning imagery.png" },
{ description: "Blue Whales enjoying the Welsh Countryside", file: "./images/Blue Whales enjoying the Welsh Countryside.png" },
{ description: "Ceci n'est pas une orange", file: "./images/Ceci n'est pas une orange.png" },
{ description: "DALL•E painting a picture", file: "./images/DALL•E painting a picture.png" },
{ description: "Dall-E drawing an image of chairs", file: "./images/Dall-E drawing an image of chairs.png" },
{ description: "Dragon Drop (1)", file: "./images/Dragon Drop (1).png" },
{ description: "Dragon Drop", file: "./images/Dragon Drop.png" },
{ description: "Echo Abstract DJ in Techno Club", file: "./images/Echo Abstract DJ in Techno Club.png" },
{ description: "Lying in bed, just like Brian Wilson did", file: "./images/Lying in bed, just like Brian Wilson did.png" },
{ description: "Raccoons howling at the moon", file: "./images/Raccoons howling at the moon.png" },
{ description: "Ships from the age of sail in space", file: "./images/Ships from the age of sail in space.png" },
{ description: "Steampunk software engineers", file: "./images/Steampunk software engineers.png" },
{ description: "That's no moon, it's a space station", file: "./images/That's no moon, it's a space station.png" },
{ description: "They went on forever – They - When I w- We lived in Arizona, and the skies always had little fluffy clouds in 'em, and, uh... they were long... and clear and... there were lots of stars at night. And, uh, when it would rain, it would all ", file: "./images/They went on forever – They - When I w- We lived in Arizona, and the skies always had little fluffy clouds in 'em, and, uh... they were long... and clear and... there were lots of stars at night. And, uh, when it would rain, it would all .png" },
{ description: "Throwing Chairs", file: "./images/Throwing Chairs.png" },
{ description: "Whales in Wales", file: "./images/Whales in Wales.png" },
{ description: "Whales playing music at a rock festival in a disney style cartoon", file: "./images/Whales playing music at a rock festival in a disney style cartoon.png" },
{ description: "Whales walking in Cardiff", file: "./images/Whales walking in Cardiff.png" },
{ description: "album cover for my new vaporwave album", file: "./images/album cover for my new vaporwave album.png" },
{ description: "architect-playing-jenga", file: "./images/architect-playing-jenga.png" },
{ description: "draw an AI robot being controlled by a raccoon", file: "./images/draw an AI robot being controlled by a raccoon.png" },
{ description: "draw raccoons writing software in anime style", file: "./images/draw raccoons writing software in anime style.png" },
{ description: "eat sleep rave repeat", file: "./images/eat sleep rave repeat.png" },
{ description: "generic handsome man", file: "./images/generic handsome man.png" },
{ description: "photorealistic image of hacker collective hacking the planet", file: "./images/photorealistic image of hacker collective hacking the planet.png" },
{ description: "pixel art image of tokyo", file: "./images/pixel art image of tokyo.png" },
{ description: "pixelart image of software construction", file: "./images/pixelart image of software construction.png" },
{ description: "presidential debate styled like a street fighter game", file: "./images/presidential debate styled like a street fighter game.png" },
{ description: "propaganda poster about not believing propaganda", file: "./images/propaganda poster about not believing propaganda.png" },
{ description: "propaganda poster about safe computing", file: "./images/propaganda poster about safe computing.png" },
{ description: "raccoon fighting a chair", file: "./images/raccoon fighting a chair.png" },
{ description: "software engineers at work", file: "./images/software engineers at work.png" },
{ description: "spinning up a new EC2 instance", file: "./images/spinning up a new EC2 instance.png" },
{ description: "taekwondo sparring in anime style", file: "./images/taekwondo sparring in anime style.png" },
{ description: "the treachery of ai generated images", file: "./images/the treachery of ai generated images.png" },
{ description: "three wolf moon but with raccoons", file: "./images/three wolf moon but with raccoons.png" },
{ description: "trophy for throwing chairs", file: "./images/trophy for throwing chairs.png" },
{ description: "vhs still image of a hypercar at night", file: "./images/vhs still image of a hypercar at night.png" },
];
}
